### PR TITLE
Fix Receiver, Transmitter handling

### LINKED ISSUE #57: How to handle Submit_SM_Resp in Transmitter connection ?
I can't figure out how to handle the Submit_SM_Resp in a Transmitter connection.

The [SMPP specification](https://smpp.org/SMPP_v3_4_Issue1_2.pdf) (page 17) says that the Submit_SM_Resp is sent in the same connection of the transmitter, but there's no way to listen for the PDU responses in the `TransmitSettings`.

Did I miss something in the library ?

### PR DESCRIPTION
**Pull request by linxGnu**
Closes #57

### CODE REVIEW

File: transmitter.go [hunk 1]
```diff
@@ -262,3 +249,67 @@ func (t *transmitter) write(v []byte) (n int, err error) {
 
 	return
 }
+
+// PDU loop processing
+func (t *transmitter) loopReceiving() {
```
Comment (linxGnu) [inline transmitter.go:254]: Handle auto-response for Transmitter

File: receiver_session.go [hunk 2]
```diff
@@ -59,7 +64,9 @@ func NewReceiverSession(dialer Dialer, auth Auth, settings ReceiveSettings, rebi
 		}
 
 		// create new receiver
-		r := NewReceiver(conn, session.settings)
+		r := newReceiver(conn, session.settings)
+		r.settings.response = r.defaultResponse
```
Comment (linxGnu) [inline receiver_session.go:68]: Hijack auto-responser

**Review by goten4 — COMMENTED** [review]
A receiver should be able to send EnquireLink too ... some SMS-C don't send it, so we need to maintain the connection.
And it should be able to send DataSM PDU too.

In my implementation, I've been a little bit heavier ;)
I renamed the `Transmitter` to `writer`, and the `Receiver` to `reader`, and all the binding types have an `in` (`reader`) and `out` (`writer`), like the `Transceiver` does. So the new `Receiver` inherits of the possibility to send EnquireLink and DataSM, and the `Transmitter` inherits the receiving part (no code duplication ;)).

**Comment by linxGnu** [comment]
@goten4 Thank you very much for reviewing.

I think your idea is great to prevent code duplication and take advantage of well testing `EnquireLink` and other handlers. I have just addressed your idea. PTAL.

Actually, I also had same idea but afraid of too many changes. After clearing my mind, I restructure a bit to avoid that.

File: transmitter.go [hunk 3]
```diff
@@ -10,88 +10,38 @@ import (
...
-type TransmitSettings struct {
-	// Timeout is timeout/deadline for submitting PDU.
-	Timeout time.Duration
-
-	// EnquireLink periodically sends EnquireLink to SMSC.
-	// The duration must not be smaller than 1 minute.
-	//
-	// Zero duration disables auto enquire link.
-	EnquireLink time.Duration
+type transmitable struct {
```
Comment (goten4) [inline transmitter.go:18]: `transmittable` ?

File: transmitter.go [hunk 4]
```diff
@@ -10,88 +10,38 @@ import (
...
 )
 
-const (
-	// EnquireLinkIntervalMinimum represents minimum interval for enquire link.
-	EnquireLinkIntervalMinimum = 20 * time.Second
-)
-
 var (
 	// ErrTransmitterClosing indicates transmitter is closing. Can not send any PDU.
 	ErrTransmitterClosing = fmt.Errorf("Transmitter is closing. Can not send PDU to SMSC")
```
Comment (goten4) [inline transmitter.go:15]: Maybe this error should be renamed to something more generic ?
```
	// ErrConnectionClosing indicates connection is closing, can not send any PDU.
	ErrConnectionClosing = fmt.Errorf("connection is closing, can not send PDU to SMSC")
```
Just an hint, my IDE suggests me that error string should not be capitalized or end with punctuation.

File: transmitter.go [hunk 5]
```diff
@@ -243,21 +184,13 @@ func (t *transmitter) check(p pdu.PDU, n int, err error) (closing bool) {
...
 
 	if err == nil {
-		if n, err = t.conn.Write(v); err != nil &&
-			n == 0 &&
-			hasTimeout &&
-			t.conn.SetWriteTimeout(t.settings.Timeout<<1) == nil {
-			// retry again with double timeout
-			n, err = t.conn.Write(v)
-		}
+		n, err = t.conn.Write(v)
```
Comment (goten4) [inline transmitter.go:193]: Just for my knowledge ... why do you remove retrying ?

**Review by goten4 — COMMENTED** [review]
LGTM ... very good indeed, great job !

Some really meaningfull details :
- You can rename files `receiver*.go`, `transceiver*.go` and `transmitter*.go` to `...able*.go`
- You can move the `connect()` function from `utils.go` to `connect.go`
- You can create a method `writePDU()` in `transmittable` and remove `marshal()` function from `utils.go`

File: example/main.go [hunk 6]
```diff
@@ -31,33 +31,31 @@ func sendingAndReceiveSMS(wg *sync.WaitGroup) {
...
 
-	trans, err := gosmpp.NewTransceiverSession(gosmpp.NonTLSDialer, auth, gosmpp.TransceiveSettings{
-		EnquireLink: 5 * time.Second,
+	trans, err := gosmpp.NewSession(
+		gosmpp.TRXConnector(gosmpp.NonTLSDialer, auth),
+		gosmpp.Settings{
+			EnquireLink: 5 * time.Second,
 
-		WriteTimeout: time.Second,
+			WriteTimeout: time.Second,
```
[the remark this answers is not in the document]
Comment (linxGnu) [reply example/main.go:39]: Yeah, let me update the example :+1: it's a good catch :heart:

File: transmitter.go (hunk 4 above)
Comment (linxGnu) [reply transmitter.go:15]: Yeah, it's great suggestion. I will address this

File: transmitter.go (hunk 5 above)
Comment (linxGnu) [reply transmitter.go:193]: I refresh my mind if I should retry. 
- In case of broken connection or SMSC fail handling
- SMPP not support multiplexing

Due to those reasons, retrying won't help in sending PDU to SMSC successfully.

Comment (goten4) [reply transmitter.go:193]: :+1:

**Comment by linxGnu** [comment]
@goten4 Renaming file will happen in another PR.

The reason is: github could not detect combo of renaming + modifying at the same time -> it will be very hard to review the logic changes in each file

That's why it's better to rename files in another PR

**Comment by goten4** [comment]
LGTM :+1:

**Comment by bachhh** [comment]
lgtm, from what I see, PDU handling for Transmitter and SubmitPDU for receiver should be in a separated PR right ?

**Comment by linxGnu** [comment]
Thank you very much for reviewing @goten4 @bachhh 

@bachhh this PR merge handling logic of TX, RX, TRX into one. They are just different from each other in binding type.

It's user responsibility to invoke `session` correctly:
- If they bind TX, then they should use `session.TX.SubmitPDU`
- If they bind RX, then they should invoke `session.RX.....`

**Review by bachhh — APPROVED** [review]
